#!/bin/bash

set -xe

timedatectl set-timezone "Asia/Shanghai"

# setup hosts cockpit
echo "127.0.0.1 cockpit" >> /etc/hosts

systemctl daemon-reload

# disable firewalld
systemctl disable --now firewalld &> /dev/null || true
setenforce 0 || true

# enable service
systemctl enable --now osbuild-composer.socket osbuild-local-worker.socket cockpit.socket
systemctl enable --now podman
#systemctl enable --now pmlogger.service || true
#systemctl enable --now pmproxy.service

netstat -anpt |grep 9090

cat >> ~/.bashrc << EOF
# github.com/yifengyou/bash
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l.='ls -d .* -a --color=auto'
alias ll='ls -l -h -a --color=auto'
alias ls='ls -a --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias push='git push'


# History setting
export PROMPT_COMMAND="history -a"
export HISTTIMEFORMAT="%F %T "
export HISTSIZE=10000

# Proxy settings
#export http_proxy='127.0.0.1:5050'
#export https_proxy='127.0.0.1:5050'
#export ftp_proxy='127.0.0.1:5050'

#export http_proxy=
#export https_proxy=
#export ftp_proxy=

PS1='\[\e[32;1m\][\[\e[31;1m\]\u\[\e[33;1m\]@\[\e[35;1m\]\h\[\e[36;1m\] \w\[\e[32;1m\]]\[\e[37;1m\]\\\$\[\e[0m\] '
EOF

chpasswd <<<"root:rocky"
echo ""
echo ""
echo "root password : rocky"
echo ""
echo ""

echo "All  done!"

exec /bin/bash
